### PR TITLE
problem: zproject out of date

### PR DESCRIPTION
**Pull request by wesyoung**
solution: regen zproject

### CODE REVIEW

**Comment by bluca** [comment]
There's a change missing? See CI failure

**Comment by wesyoung** [comment]
ha- there's a real @me ... sorry meant @wesyoung :)

**Comment by bluca** [comment]
Still shows a diff - make sure to have libzmq checked out in the same parent directory as zyre and czmq, with that exact name "libzmq"

**Comment by wesyoung** [comment]
i just realized that- i think i've run into this problem before based on the way i setup my vagrant bits.  you'd think i would have updated them last time around- NOPE>>>

**Comment by wesyoung** [comment]
i think the other part of the problem is- when i first PR'd this:

https://github.com/zeromq/zproject/blob/master/zproject_vagrant.gsl#L31

i didn't embed those checkouts to the local dir, which is what i use as a template (so i don't have to remember things). need to clean that up too i guess.

**Comment by bluca** [comment]
Thanks!

**Pull request merged**
