### PR TITLE
Added API to set Ephemeral TCP port for beacon

### PR DESCRIPTION
**Pull request by stephan57160**
This patch should allow to bypass firewalls on the same host than the ZYRE-application, when they use BEACON discovery.
See conversation on issue #323.

### CODE REVIEW

**Comment by bluca** [comment]
As the documentation and the comments in the source files say, zyre uses zproject for API management and generation: https://github.com/zeromq/zproject
So you have to add the API to this file first otherwise it will get automatically removed when the regeneration happens: https://github.com/zeromq/zyre/blob/master/api/zyre.api

Also a couple of notes:
1) It's a new API, so it must be marked as DRAFT as per the C4 process
2) The function name could be a bit more specific, as it's pretty vague at the moment. Maybe it could mention that it's the port it will be used to listen for peer-to-peer messages.

**Comment by stephan57160** [comment]
Argh. I was looking for zyre_set_port in .api, but missed this "set port" :-)
I'll update that shortly.

Regarding the notes:
1) Is there any doc, about the C4 process ?
  Shall I simply add #ifdef ZYRE_BUILD_DRAFT_API around ?
2) Initially, I thought of set_listening_port, but found that ephemeral was more specific :-)

**Comment by stephan57160** [comment]
zyre.api updated.

Regarding the function name, as other parts of the existing documentation also mention the "ephemeral port"... this looks good for me. At least, I don't have better idea, at the moment ...

Anyway, some proposals below ...
- set_listening_ephemeral_port()
- set_listening_p2p_port()
- ...

**Comment by bluca** [comment]
You also need to regenerate with zproject - if you are on Linux, you can just install the zproject and gsl packages from our OBS repos:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-stable&package=zproject

And then run ```gsl project.xml``` from the zyre root.

**Comment by stephan57160** [comment]
Thx.

**Pull request merged**
