### PR TITLE
Add a build example for minimal.c when not using pkg-config, i.e. you…

### PR DESCRIPTION
**Pull request by ghenry**
…'ve built zyre from source following the guide in README.md

### CODE REVIEW

**Comment by bluca** [comment]
you should always use pkg-config, as that will break very easily

**Comment by ghenry** [comment]
Does that work when building from source following https://github.com/zeromq/zyre#building-on-linux-and-macos ?

```
gcc `pkg-config --libs --cflags libzyre` minimal.c -o minimal
Package libzyre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzyre.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzyre' found
/usr/bin/ld: /tmp/ccXE1qBd.o: in function `main':
minimal.c:(.text+0x52): undefined reference to `zyre_new'
/usr/bin/ld: minimal.c:(.text+0x8a): undefined reference to `zyre_start'
/usr/bin/ld: minimal.c:(.text+0x9d): undefined reference to `zyre_join'
/usr/bin/ld: minimal.c:(.text+0xcd): undefined reference to `zyre_shouts'
/usr/bin/ld: minimal.c:(.text+0xd7): undefined reference to `zclock_sleep'
/usr/bin/ld: minimal.c:(.text+0xe3): undefined reference to `zyre_recv'
/usr/bin/ld: minimal.c:(.text+0xf3): undefined reference to `zmsg_print'
/usr/bin/ld: minimal.c:(.text+0xff): undefined reference to `zmsg_destroy'
/usr/bin/ld: minimal.c:(.text+0x10a): undefined reference to `zsys_interrupted'
/usr/bin/ld: minimal.c:(.text+0x121): undefined reference to `zyre_stop'
/usr/bin/ld: minimal.c:(.text+0x12d): undefined reference to `zyre_destroy'
collect2: error: ld returned 1 exit status
```

Thanks.

**Comment by bluca** [comment]
You need to use the appropriate flags and env vars, you should be able to find information online

**Comment by ghenry** [comment]
What I want to do is update the docs to save others time like I've just spent and also taken the time to do a PR. If the docs are wrong, let me know how and I'll take more time to do another PR. 

If you suggest information online, please take the time to link to it in your suggestion so others can find it. Sigh....What I needed to do, I've done and provided a doc PR to help others. Reject it if incorrect.

**Comment by bluca** [comment]
it's fine, for simple use cases it will work

**Comment by ghenry** [comment]
Which is what I think the source code comment is really saying. Do we want to add some docs to the main README.md for it?

**Comment by bluca** [comment]
no need, i'ts ok

**Comment by ghenry** [comment]
I'll add, `libzyre.pc` does get installed (as I'm sure you know):

```
ls -lh /usr/local/lib/pkgconfig/libzyre.pc
-rw-r--r-- 1 root root 965 Feb  4 14:09 /usr/local/lib/pkgconfig/libzyre.pc

$ cat /usr/local/lib/pkgconfig/libzyre.pc
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libzyre
Description: an open-source framework for proximity-based P2P apps
Version: 2.0.1

Requires.private:  libzmq
Libs: -L${libdir} -lzyre
Cflags: -I${includedir} -DZYRE_BUILD_DRAFT_API=1
Libs.private:  -lczmq

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
```
so this would be my local pkg-config not having /usr/local/lib/pkgconfig in it's path includes or a `configure` option?

What should the install guide for Linux distros have in it for this to just work?

Thanks.

**Comment by ghenry** [comment]
If I do this, all is fine:

`gcc `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ pkg-config --libs --cflags libzyre libzmq libczmq` minimal.c -o minimal`

```
ls -1 /usr/local/lib/pkgconfig/
libczmq.pc
libsodium.pc
libzmq.pc
libzyre.pc
```

should I update the docs for this example?

Thanks.

**Pull request merged**
