### PR TITLE
Problem: SILENT event was not declared in the API

### PR DESCRIPTION
**Pull request by stvales**
Solution: add it ;-)

### CODE REVIEW

**Comment by bluca** [comment]
All the builds are broken, please check again:

```
src/zre_msg.c:38:32: fatal error: ../include/zre_msg.h: No such file or directory
```

@keent as per the C4.1 process, please wait for the CI before merging a PR, to ensure no obvious regressions are introduced. Thanks!

**Comment by keent** [comment]
@bluca Copy. Should I revert?

**Comment by bluca** [comment]
Let's wait a few minutes to see if @stvales is around to fix it

**Comment by stvales** [comment]
I’m on it !

**Pull request merged**
