### PR TITLE
Regenerate from zproject

### PR DESCRIPTION
**Pull request by benjdero**

### CODE REVIEW

**Comment by sphaero** [comment]
could you try to delete the .github/workflows/CI.yaml to regenerate it?

Not sure if it works but it might fix the macos build issues

**Comment by benjdero** [comment]
@sphaero What do you mean "to regenerate it"? I'm not sure to understand.

**Comment by benjdero** [comment]
It still fails after forcing CI.yaml to regenerate.

**Comment by sphaero** [comment]
yes but at least it runs now and is giving a sane error.

```
  * zyre-curve: D: 24-08-05 13:21:22 (node6) cannot connect to endpoint=tcp://(null):49152
Assertion failed: (msg), function zyre_test, file zyre.c, line 1107.
```
Apparently zyre doesn't run on MacOS currently. Build also fails on Windows during czmq build.

**Comment by sphaero** [comment]
why did you undo the changes? Or did I miss something?

**Comment by benjdero** [comment]
Hi @sphaero ,

What can I do to help this PR get merged?

**Comment by sphaero** [comment]
You need to include all the files generated by zproject (git status shows which) and rebuild the .github/workflows/CI.yaml like you did before. The project is very outdated I believe

**Comment by sphaero** [comment]
@benjdero I've created a new PR #742 which includes all files and fixes. Perhaps you can merge that?

**Comment by benjdero** [comment]
Closing since those changes are embedded into #742

**Comment by sphaero** [comment]
I can give you permission if you want. Just follow [C4](https://rfc.zeromq.org/spec/42/)
I can't merge either

**Comment by sphaero** [comment]
I've added you to the maintainers. In the meantime @bluca already merged #742.

**Comment by benjdero** [comment]
Yeah, I was reading C4 to make sure everything was alright before I approve it but @bluca was faster. Maybe next time! ;)

**Pull request closed without merging**
