### PR TITLE
Problem: Travis build fails, zproject out of date. 

### PR DESCRIPTION
**Pull request by sphaero**
Solution: regenerate zproject, add valgrind script

### CODE REVIEW

**Comment by bluca** [comment]
Note that zproject won't update the travis.yml if it already exists, so if you want to add the Valgrind run you need to copy and commit it manually, with something like:

https://github.com/zeromq/czmq/commit/dea7053538a57305639970190c1b6dec55e3c2b3

```
matrix:
  include:
  - env: BUILD_TYPE=valgrind
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
        - valgrind
```

**Comment by sphaero** [comment]
I have no idea about the valgrind tests. The check_zproject test was failing because the valgrind scripts generated by zproject were not added to the zyre repository. 

We were working on this saturday with @sappo to get a clean travis test again :)

**Comment by sappo** [comment]
@sphaero awesome thanks for seeing this through :+1:

**Comment by sphaero** [comment]
yeah, after what we tried saturday I couldn let go of it :)

**Comment by sappo** [comment]
@sphaero now it's up to @gotcha to re-introduce his docker build ;)

**Pull request merged**
