### PR TITLE
Problem: Outdated Python binding file #468

### LINKED ISSUE #468: Problem: Outdated Python binding file
https://github.com/zeromq/zyre/blob/master/bindings/python/zyre.py (mostly) duplicates https://github.com/zeromq/zyre/tree/master/bindings/python/zyre and is probably a relic from an old auto-generation.

Solution: Delete https://github.com/zeromq/zyre/blob/master/bindings/python/zyre.py

### PR DESCRIPTION
**Pull request by papr**
Solution: Delete old file

Fixes #468

### CODE REVIEW

**Comment by sappo** [comment]
What about https://github.com/zeromq/zyre/blob/master/bindings/python/test.py is that still used? @sphaero 

I deleted it and zproject didn't re-generate it!

**Comment by papr** [comment]
Actually, `zproject` is generating Python 2.7 incompatible code! `zyre_print` is mapped to `Zyre.print`. This leads to an syntax error.

Code to reproduce problem:
```python
class A(object):
    def print(self):
        pass

a = A()
a.print()
```
This problem arises from `print` being a keyword in Python 2.7 instead of an function. In Python 3 print is a function and therefore compatible with above code.

Solution: `zproject` has to look for this special cases and rename the generated functions accordingly.

**Comment by papr** [comment]
Opened zeromq/zproject#645.

**Comment by twhittock** [comment]
It uses from __future__ import print

So it is correct code

**Comment by papr** [comment]
@twhittock You are correct. Adding `from __future__ import print_function` fixes the problem.

@sphaero @sappo https://github.com/zeromq/zyre/blob/master/bindings/python/test.py#L16 is outdated as well. It uses the old API. The test fails on line 16. It should be `ZyreEvent.peer_name()` instead of `ZyreEvent.name()`.

The question is, where the auto-generated test file is if not in this folder?

**Comment by twhittock** [comment]
The file was hand written by me. It mirrors the hand written c test cases
in an attempt to impede bit rot  :)

**Comment by sphaero** [comment]
@sappo Iḿ not sure it ever did. Perhaps they were handwritten by @twhittock? I can't recall.

**Comment by twhittock** [comment]
I think I forgot to add python test case to Travis.  I did it for czmq but
possibly not zyre. Please don't delete it I'll try to get it working and
integrated with ci when I have a chance.
On 29 Jun 2016 9:13 a.m., "Arnaud Loonstra" <notifications@github.com>
wrote:

@sappo <https://github.com/sappo> Iḿ not sure it ever did. Perhaps they
were handwritten by @twhittock <https://github.com/twhittock>? I can't
recall.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/zeromq/zyre/pull/469#issuecomment-229287416>, or mute
the thread
<https://github.com/notifications/unsubscribe/AGDEBxmbFTXFe126b9ZYMoyoLCc8OneGks5qQilFgaJpZM4JAN4r>
.

**Pull request merged**
