### PR TITLE
Problem: Out of sync with zproject

### PR DESCRIPTION
**Pull request by sappo**
Solution: Re-generate!

### CODE REVIEW

**Comment by bluca** [comment]
For some reasons it's still trying to use gradle 2.13, I had the same issue:

```
Downloading https://services.gradle.org/distributions/gradle-2.13-bin.zip
```

**Comment by sappo** [comment]
It's trying to build to czmq JNI wrapper which currently still uses gradle 2

**Comment by sappo** [comment]
We need to merge https://github.com/zeromq/czmq/pull/1967 first

**Comment by bluca** [comment]
> It's trying to build to czmq JNI wrapper which currently still uses gradle 2

D'oh! Completely missed that. Merged the other PR and restarted the job, let's see

**Comment by bluca** [comment]
I know what the problem is now, I'll fix that - thanks for updating gradle

**Comment by sappo** [comment]
You're welcome

Am So., 16. Dez. 2018, 20:02 hat Luca Boccassi <notifications@github.com>
geschrieben:

**Pull request merged**
