### PR TITLE
Problem: not aligned with zproject

### PR DESCRIPTION
**Pull request by mjvankampen**
Fix: regenerate zproject

Ref. https://github.com/zeromq/zproject/issues/1266

### CODE REVIEW

**Comment by sphaero** [comment]
Seems you missed some commits? Can you add those? Check the log of travis: 

```+git --version

git version 2.27.0

++git --no-pager diff -w

+[[ -n diff --git a/bindings/python_cffi/zyre_cffi/cdefs.py b/bindings/python_cffi/zyre_cffi/cdefs.py

index ac26725..f8b259e 100644

--- a/bindings/python_cffi/zyre_cffi/cdefs.py

+++ b/bindings/python_cffi/zyre_cffi/cdefs.py

@@ -501,10 +501,6 @@ void

 zlistx_t *

     zcertstore_certs (zcertstore_t *self);

 

-// Return the state stored in certstore

-void *

-    zcertstore_state (zcertstore_t *self);

-

 // Self test of this class

 void

     zcertstore_test (bool verbose); ]]

+git --no-pager diff -w

diff --git a/bindings/python_cffi/zyre_cffi/cdefs.py b/bindings/python_cffi/zyre_cffi/cdefs.py

index ac26725..f8b259e 100644

--- a/bindings/python_cffi/zyre_cffi/cdefs.py

+++ b/bindings/python_cffi/zyre_cffi/cdefs.py

@@ -501,10 +501,6 @@ void

 zlistx_t *

     zcertstore_certs (zcertstore_t *self);

 

-// Return the state stored in certstore

-void *

-    zcertstore_state (zcertstore_t *self);

-

 // Self test of this class

 void

     zcertstore_test (bool verbose);

+echo 'There are diffs between current code and code generated by zproject!'

There are diffs between current code and code generated by zproject!
```

**Comment by sappo** [comment]
Double checked it. Travis is wrong!

**Comment by sphaero** [comment]
Huh, what happened?

**Comment by sappo** [comment]
Not sure :man_shrugging:

**Pull request merged**
