### PR TITLE
Problem: some generated files are not in the gitignore file

### PR DESCRIPTION
**Pull request by zguangyu**
Solution: add some generated files into gitignore file.

### CODE REVIEW

**Comment by bluca** [comment]
Thanks for the PR, but please follow the contributing guidelines:

https://github.com/zeromq/zyre/blob/master/CONTRIBUTING.md

Specifically, commits should be framed as "Problem: ... Solution:..."

What problem are you aiming to solve exactly by moving the cmake file? It will break a few things.

**Comment by zguangyu** [comment]
The main problem I want to solve is to add an option for the example. Then I can turn it off when I don't need it. 

I have to say that moving the cmake file will not solve any problem. I just think that it is more clear to have a cmake file under the same directory of the example. In the main cmake file I can use the option to control whether to add_subdirectory(example/chat) or not. Well, this can be discussed.  If you think this is not a good idea, I can split this pr into two.

In fact the original problem I want to solve is that the example/chat/chat is not in the gitignore file. I added this project as a submodule in my project. It always shows untracked content in the git status.

**Comment by zguangyu** [comment]
I found that the CMakeLists.txt is generated by gsl, and the option should be defined in the project.xml. Is it necessary to name it CMakeLists-local.txt for a cmake file not generated by gsl?

**Comment by bluca** [comment]
> I have to say that moving the cmake file will not solve any problem. I just think that it is more clear to have a cmake file under the same directory of the example. In the main cmake file I can use the option to control whether to add_subdirectory(example/chat) or not. Well, this can be discussed. If you think this is not a good idea, I can split this pr into two.

That file is a project local hook, and it does not belong in the examples directory, so please remove that commit.

> I found that the CMakeLists.txt is generated by gsl, and the option should be defined in the project.xml. The output summary of cmake is hard coded in the zproject, so it is not possible to customize it to add our own option, right?

The examples is a local setting of zyre, so it should be entirely constrained in the project local hook. You can add status output there. Please remove all changes from the top level cmake file, and instead add the option to the local hook.

**Comment by zguangyu** [comment]
I'm not familiar with zproject. I need to take some time to figure out the local hook. Let me split it into two prs. First one is the gitignore thing. This can temporarily solve my problem. I will make another pr for the option.

**Pull request merged**
