### PR TITLE
Problem: NEWS out of date

### PR DESCRIPTION
**Pull request by bluca**
Solution: list major changes

### CODE REVIEW

**Comment by mvala** [comment]
Can we include info what version of czmq and zmq is needed. Thanks

**Comment by bluca** [comment]
There shouldn't be any restrictions

**Comment by mvala** [comment]
Does it mean that we can use it with CZMQ 4.0.2?

**Comment by bluca** [comment]
Yes

**Comment by sappo** [comment]
Great job, thanks @bluca

**Pull request merged**
